### ISSUE TITLE
Add RN CLI Dependency

### ISSUE THREAD

**Issue by mcavaliere** [echobind/react-native-template#127]
The CLI is now installed as a dependency from [@react-native-community/cli](https://github.com/react-native-community/cli), so we can package it with the template.

**Comment by cmejet** [comment]
@mcavaliere Do you think we need it? We've been using npx and haven't had to install it. Just curious about your thoughts.

**Comment by cball** [comment]
I think we can close this, since the global install has been deprecated for some time.
