### ISSUE TITLE
Add state and headers setup for Apollo

### ISSUE THREAD

**Issue by gprocell927** [echobind/react-native-template#19]
If GraphQL is something we are regularly going to use for our APIs, it would be nice to be able to startup the template with a basis for a client and some sort of groundwork set up for a state tree.

**Comment by cball** [comment]
We might want to do this with a prompt. If Hygen is installed as a dev dependency and run with npx, I'm thinking we can just run a generator template to install state management. it would prompt for Apollo/MST/Redux

**Comment by cball** [comment]
outdated, we're all Apollo now.
