### ISSUE TITLE
Add test coverage reporting tool

### ISSUE THREAD

**Issue by mcavaliere** [echobind/react-native-template#93]
Add a tool for visualized coverage reporting. [Istanbul.js](https://istanbul.js.org/) is one, there are probably a number of others

* Research what tool would be best for the project
* Integrate it with jest (probably in a `test:coverage` command)
* Ensure it works with CircleCI (or any other CI we might use)

**Comment by cball** [comment]
Going to close this since we can use the built-in `--coverage` command for jest (which uses istanbul)
